### ISSUE TITLE
0.7 bot can't find key bindings

### ISSUE THREAD

**Issue by Crasben** [Zemogus/Holocure-Auto-Fishing-Bot#3]
I'm getting this error `System.Exception: settings.json was not formatted correctly. Could not find key bindings.
   at Holocure_Auto_Fishing_Bot.Program.GetSettings()
   at Holocure_Auto_Fishing_Bot.Program..cctor()`
   when i open the program with HoloCure 0.7

**Comment by v5tge** [comment]
+1

**Comment by SummerChu** [comment]
If you know how to compile the code, it's a really easy fix:
Edit line 441 of Program.cs so that the 5 is a 6.

**Comment by TemariVirus** [comment]
Changed it so that the regex will match at least 6 buttons, so hopefully this won't be an issue if Kay Yu adds even more buttons in the future. But future updates will probably break it in other ways, won't they lol.
